# Generated by Django 5.2.1 on 2025-06-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adventure',
            options={'ordering': ['-created_at']},
        ),
    ]
